version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: thursday
      time: "12:00"
      timezone: Europe/Athens
    open-pull-requests-limit: 10
    reviewers:
      - MartijnCuppens
      - XhmikosR
    labels:
      - dependencies
    versioning-strategy: increase
