language: node_js
git:
  depth: 3
node_js:
  - "6"
  - "8"
  - "10"
install:
  - npm install
script:
  - npm test || travis_terminate 1
cache:
  directories:
    - node_modules
    - vendor/bundle
notifications:
  email: false
